[workspace]
members = [
    "src/engine/core",
    "src/engine/capi",
    "src/engine/cffi",
    "src/engine/dict",

    "src/frontends/wayland",
    "src/frontends/xim",

    "src/tools/check",
    "src/tools/indicator",
    "src/tools/log",
    "src/tools/version",
]

[profile.release]
lto = true
