[workspace]
members = [
    "src/daemon/indicator",

    "src/log",
    "src/version",

    "src/engine/core",
    "src/engine/capi",
    "src/engine/cffi",

    "src/frontends/wayland",
    "src/frontends/xim",
]

[profile.release]
lto = true
