---
layout: dubeolsik
global_hangul_state: false
word_commit: false
hotkeys:
  Super-Space:
    behavior: ToggleHangul
    result: Consume
  Esc:
    behavior: ToEnglish
    result: Bypass
  Muhenkan:
    behavior: ToggleHangul
    result: Consume
  AltR:
    behavior: ToggleHangul
    result: Consume
  Hangul:
    behavior: ToggleHangul
    result: Consume
layout_addons:
  all:
    - ComposeChoseongSsang
  dubeolsik:
    - TreatJongseongAsChoseong
xim_preedit_font:
  - D2Coding
  - 15.0

