---
default_category: Latin
global_category_state: false
icon_color: Black
global_hotkeys:
  M-C-Backslash:
    behavior:
      Mode: Math
    result: ConsumeIfProcessed
  Super-Space:
    behavior:
      Toggle:
        - Hangul
        - Latin
    result: Consume
  M-C-E:
    behavior:
      Mode: Emoji
    result: ConsumeIfProcessed
  Esc:
    behavior:
      Switch: Latin
    result: Bypass
  Muhenkan:
    behavior:
      Toggle:
        - Hangul
        - Latin
    result: Consume
  AltR:
    behavior:
      Toggle:
        - Hangul
        - Latin
    result: Consume
  Hangul:
    behavior:
      Toggle:
        - Hangul
        - Latin
    result: Consume
category_hotkeys:
  Hangul:
    ControlR:
      behavior:
        Mode: Hanja
      result: Consume
    HangulHanja:
      behavior:
        Mode: Hanja
      result: Consume
    F9:
      behavior:
        Mode: Hanja
      result: ConsumeIfProcessed
mode_hotkeys:
  Math:
    Enter:
      behavior: Commit
      result: ConsumeIfProcessed
    Tab:
      behavior: Commit
      result: ConsumeIfProcessed
  Hanja:
    Enter:
      behavior: Commit
      result: ConsumeIfProcessed
    Tab:
      behavior: Commit
      result: ConsumeIfProcessed
  Emoji:
    Enter:
      behavior: Commit
      result: ConsumeIfProcessed
    Tab:
      behavior: Commit
      result: ConsumeIfProcessed
xim_preedit_font:
  - D2Coding
  - 15.0
latin:
  layout: Qwerty
  preferred_direct: true
hangul:
  layout: dubeolsik
  word_commit: false
  addons:
    all:
      - ComposeChoseongSsang
    dubeolsik:
      - TreatJongseongAsChoseong
