[package]
name = "kime-indicator"
version = "0.1.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
kime-version = { path = "../version" }
kime-log = { path = "../log" }

glib = "0.10.3"
gio = "0.9.1"
gobject-sys = "0.10.0"
gtk-sys = "0.10.0"
libappindicator-sys = "0.5.0"
log = "0.4.14"
anyhow = "1.0.38"
simplelog = "0.9.0"
pico-args = "0.4.0"
daemonize = "0.4.1"
xdg = "2.2.0"
