[package]
name = "kime-engine-backend-hangul"
version = "0.1.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
kime-engine-backend = { path = "../../backend" }
enumset = "1.0.6"
num-derive = "0.3.3"
num-traits = "0.2.14"
serde = { version = "1.0.124", features = ["derive"] }
serde_yaml = "0.9"

[target.'cfg(unix)'.dependencies]
xdg = "2.2.0"
