[package]
name = "kime-engine-candidate"
version = "0.1.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2021"
license = "GPL-3.0-or-later"

[dev-dependencies]
kime-engine-dict = { path = "../dict" }

[dependencies]
nix = "0.26.1"
