[package]
name = "kime-engine-cffi"
version = "0.8.1"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"
license = "GPL-3.0"

[features]
nightly = []

[dependencies]
cty = "0.2.1"

[build-dependencies]
bindgen = { version = "0.57.0", default-features = false }
cbindgen = { version = "0.18.0", default-features = false }
